---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cloudflare-tunnel-ingress-controller
spec:
  encryptedData:
    api-key: AgAu3EXzr+KAOg4nFqxgIYPqIVMMomKKIIITkv+NfcKlQriYebpAY0k38b1Pl//0razXcHMu1Z29Y4o7VVpU2/lLJbnpf9at6uW6yAUNxRfV+6WuTIMUglnBaKP6Xonujzmx4l9FhXFg3+SV9uGHA/QnVIDQsOT9fUia4B5qZpeTPAA5APN9Ma6ujYqnrLK2k6jG/zX7AzZEA47m52Snd+AtFIkWwJj1TrvtDnASuC0tqiE1CMGQtcmR/0IqMCg7VPGAJRKQw3NG+zcHNucPkvqFIYZmZe+qzjHN1xy5+1IJ6Ed6NPc/ov++Ixbv6D12LDuGj/FhHta90G+lXRXgNZ1l5EkO3hW3MQwMjtOc+RYzuiBbwpB7nlvUY0czkfJS1/ZEZGKhVm+PrIuzOiWdkyOCVcpa8iqYK2uHgoAkXNZTOJgODpA419gM+PK5+yFljUlsDylNZzZE1/1Fh6bIETB37huaYtiwUROYrJl6pKeMNk8dlbqFfGRu+zINSveybsvSa6uyp6XayOprVek6NEtvch6hd2ARE+mVpEnLD86vRJAG1Kc4UczhfY5v8Bie1sNbaBxKg5Q8LHLhQrfti+oyAnH/YK29XEa+nXhob1bYE3ff4VoUQCAjQOi8E/WhBWgfuv/s0zzSiqjZr10yuy7kghLubnaeAZxyiQ6YJzi0iY5Xa0tY0Za/w5BX7WpNE8+GbbG2mdGQxRxrMjmgMsE4qDMx3b6F9SYdCGRaSNR+0m3t1AULds0z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cloudflare-tunnel-ingress-controller
    type: Opaque
