---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBISzDeFrChIb+xlDgSUgSIRAC8Pf/IBuVOib1QxSy4NgGIXCeUQjKOH5QobUvmfOLu4WQemJEoMims638kTMidoeaUVhSeq8Ld+QCIGcLnAe4l/Z764EamEH9vEO4nAYctqI2pawlryQjUGUwRuzD8P7RlHnXym27vMJFOMxsbuNknNm1gJSaBVGuudZJq5NxNr+9bQ3ESVq+wAQhVBNAh7l7cqqbLC8az9641zRI4UAkzKXbsDdOo9PwxxfDnUTT2m8+c5S17m3N2e8URJucATwrWyxoNXc9nmdayDWVoHlHdd9uO4KqNoMo92WpRxVZBieKGBjvJcXJqnF25tqfwvuG/4avjmBx+ug/jgmJ4x3biRysq3630hqh/VlXBNwuyM6NRRkYDMnqQohDOb9bgWuIzS1T287CCcQFZz9ocg7uXwCzxZ0Hipt4z5T3Cs4YvNbt2mi+tW+a98FFfpA69upZikPzO6JffY3MW80HZNHSiHr0NWh9luq4xlwt/QuUnC3FlrJjVhHgg4WcXaasD57Jyitj8Y/cAlOli2eXNjeK2F6RXfjdygBuQYlyA7Gicfq/C27OGZ++df1rhM4lgaRIPiyz3HmZMTyDiwTUlkjio1moXUp7aI9sjoRIy4aNzOPU0elOWulpaLqXKFpeEspZnA/+Mnd6c/8vdZR0AUMGP63ScqmtBxiUIE+tkKPKSAdYk7iWP80aVaNZnM1hwkU4JWAVHvrPu1LYTBLauvA==
    admin-user: AgBnAd/tDAJLQxEGOtSpSdottTEOv+8BlLYeNptaLg+MAwjbwMkqYekWlUWfxbAkQZ42XzZ7BH3c4hb+WfuTV5G/vlw1MYQ63eVTTUCLqgcb8zSCGl2yhtb0PDe4i8RkNzP3KqRPoHk4/6khIyvXIqZRd2IHRNGDbcERgX0ArsjwS7GCr4tVdBdxghXgn0giSXwjqSaDuBxZolS1tGflFgkQnetUaHSdAfwqYERGFSBYEM9FjoaARjUFZKiJ69q1P+KpCs6B39o2F8wQTQO1BWr8dQTNvnxtCcyYovWnvxuR9oWJBNoobGVDz1MMXbCVa1ZIHM//y1VOUzfSD0q39Qw5/xPSjzIkvPWzD1BYGNa2KGkyOoWDIyk/vsQkc+RBdAXUR7shQXckoOo34T0pQLWy/cKr7sqtLyankYOMkzbSkNCzI7AJNAQoxnP/xuqlhbwIbAHgH7LSMCgk4QTmzoLw4cuLL0kywvlAukRJO9GNv7LUwZ1HmjCxOkiWiu+5o8CuSprrRRvBPFdsYpOB0xnd4MrQGgfQwhqQfm22YWpj752/Fhy66AiIeoQtZFEbRxpQqDpzVACH3CTyflGcF6ylX+5rAhe1McJps/mnWBo0sTSvWumkvHu9a+VcRLDIzTX2xVVlPd73po7Np2lUoP4TMx2p5zX+Bs1INiTkaaIb9fFAAGLdyXrHlP3qwaYx/kB2F1QWMw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: grafana
    type: Opaque
